version: '3'
services:
  ansible:
    container_name: ansible
    build: docker/ansible
    environment:
      HOME: /root
    tty: true
    working_dir: /root
    volumes:
      - ./ansible:/root/ansible
  wordpress:
    container_name: ansible-on-docker_wordpress
    build: docker/wordpress
    depends_on:
       - db
    ports:
       - "9000:80"
    volumes   :
       - ./bedrock:/var/www/bedrock
       - mysql_sock:/var/run/mysqld
       - ./log/nginx:/var/log/nginx
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - mysql_sock:/var/run/mysqld
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./log/mysql/:/var/log/mysql
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  mysql_sock:
