---
- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/var/www/wordpress/

- name: fetch composer installer
  shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: install composer
  shell: php composer-setup.php

- name: remove comper-setup.php
  shell: php -r "unlink('composer-setup.php');"

- name: set composer command
  shell: mv composer.phar /usr/local/bin/composer

- name: create wordpress owner directory
  file: path=/var/www/bedrock
        state=directory
        owner=wordpress
        group=wordpress
        mode=0774

- name: set composer command
  shell: composer create-project roots/bedrock
  args:
    chdir: /var/www/
    creates: '/var/www/bedrock/composer.json'

- name: composer install
  shell: composer install
  args:
    chdir: /var/www/bedrock/

- name: Change ownership of WordPress installation
  file: path=/var/www/bedrock/
        owner='www-data'
        group='www-data'
        state=directory
        recurse=yes

- name: Install pip
  apt:
    name: python-mysqldb
    state: present

- name: Start php-fpm Service
  service: name=php7.0-fpm state=started enabled=yes
